### ISSUE TITLE
Text gets truncated

### ISSUE THREAD

**Issue by jjack-flash** [Nialixus/typewritertext#1]
I have four typewritertext widgets on my page.  At least one, but usually several, truncate text.  I get varying results by playing with the duration parameter.  But, I'm never able to get all four Text elements rendered fully.

In the example, it should read, "Hello and Welcome.  My name is Chris McBrien.  Builder of things. ...".

Here's the relevant widget construction:
```
return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        TypeWriterText(
          repeat: false,
          text: Text(Info.introText, textAlign: TextAlign.left, style: Theme.of(context).textTheme.titleMedium),
          duration: const Duration(milliseconds: 25)),
        TypeWriterText(
            repeat: false,
            text: Text(Info.introName, textAlign: TextAlign.left, style: Theme.of(context).textTheme.headlineLarge),
            duration: const Duration(milliseconds: 25)),
        TypeWriterText(
            repeat: false,
            text: Text(Info.introTitle, textAlign: TextAlign.left, style: Theme.of(context).textTheme.headlineLarge),
            duration: const Duration(milliseconds: 25)),
        Container(
          padding: const EdgeInsets.fromLTRB(0, 10, 0, 10),
          child: TypeWriterText(
              repeat: false,
              text: Text(Info.introDescText, textAlign: TextAlign.left, style: Theme.of(context).textTheme.titleMedium),
              duration: const Duration(milliseconds: 25)),
        ),
        //_buildProficiencyList(),
      ],
    );
```
![Screenshot 2023-08-28 165826](https://github.com/Nialixus/typewritertext/assets/59496186/3bedc825-687b-4a19-995d-13b791ab0f56)

**Comment by Nialixus** [comment]
Hi, I have tried your code multiple times but couldn't reproduce the issue that happened to you. So, I added WidgetsBinding to call the timer after the first frame is rendered. Please let me know if this problem still occurs in version ^1.9.0.

![Screen Shot 2023-08-29 at 09 14 50](https://github.com/Nialixus/typewritertext/assets/45191605/b1d92201-d42d-4295-9253-b7396edcfa8c)

**Comment by jjack-flash** [comment]
That seems to have fixed the problem.

Thanks!
