### ISSUE TITLE
The widget leaves a gap under text

### ISSUE THREAD

**Issue by vshvedov** [Nialixus/typewritertext#11]
![IMG_BFD878AC3E4B-1](https://github.com/Nialixus/typewritertext/assets/69118/987d4c07-2f3e-4b6b-8977-85a17c37db45)

![IMG_AC87094D46F9-1](https://github.com/Nialixus/typewritertext/assets/69118/9327a0ec-6f41-499e-b655-18167998bf4a)

Example code:

```
          Padding(
            // note that the bottom padding is 0
            padding: EdgeInsets.fromLTRB(10.w, 10.h, 10.w, 0),
            child: TypeWriter.text(
              story.text,
              style: TextStyle(fontSize: 18.sp),
              duration: const Duration(milliseconds: 20),
            ),
          ),
```

Expected: no padding under text

**Comment by vshvedov** [comment]
Missed the `maintainSize` attribute, which helped.

**Comment by Nialixus** [comment]
> Missed the `maintainSize` attribute, which helped.

You can still use the old version and add this

```dart
// ignore: deprecated_member_use
TypeWriterText.builder(...);
```

To ignore the lint warning of using deprecated widget

Or just downgrade back to https://pub.dev/packages/typewritertext/versions/3.0.3
