### ISSUE TITLE
Document and Example code is not updated

### ISSUE THREAD

**Issue by ishaileshmishra** [Nialixus/typewritertext#12]
Document and Example code is not updated, Please add updated code to the example and correct the readme file as well.

like  **AutoSizeText** is deprecated but is still available in the document

thanks

**Comment by Nialixus** [comment]
[#v3.0.6](https://pub.dev/packages/typewritertext/versions/3.0.6)

I've moved the deprecated to constructor instead of the class, and merged the library.

By the way, `autosizetext` isn't part of this package. It's just used as an example of how to integrate this package with another one.
