### ISSUE TITLE
onChanged callback not found

### ISSUE THREAD

**Issue by ashraf267** [Nialixus/typewritertext#13]
I was able to use the package to display texts in an array using the typewriter effect, but after each each text (or array item), I want to add a delay then resume. I saw that the "onChanged" callback in the doc seems to handle this, but surprisingly isn't present as a method in the Typewriter widget/class. Is this a bug or the "onChanged" callback func has been deprecated?

**Comment by Nialixus** [comment]
To achieve a similar functionality to `onChanged` in TypeWriter, you can either use a listener from the controller or call a function inside the builder.


## Using a listener from the controller
```dart
final controller = TypeWriterController(
  text: "Hello World",
  duration: const Duration(milliseconds: 50),
);

controller.addListener(() {
  /// Your onChanged function here
});
```

## Calling a function Inside the builder
or calling function inside the builder

```dart
TypeWriter(
   builder: (context, value) {
      WidgetsBinding.instance.addPostFrameCallback((_){
         /// Your onChanged function here
      });
      
   return Text(value.text);
});
```
