### ISSUE TITLE
Can you achieve the effect of the login interface like ChatGPT app? #1

### ISSUE THREAD

**Issue by itMcdull** [Nialixus/typewritertext#16]
First of all, thank you for your plugin, it is very good, but I recently encountered an effect like ChatGPT, which requires a vibration every time a text appears, and a quick vibration effect when it is deleted. Is it possible? Thank you very much

https://github.com/user-attachments/assets/c72d0e5e-7234-42d7-bdab-8bf7d0b02a1e

**Comment by Nialixus** [comment]
Thank you for the compliment! 

I'm not entirely sure what you mean by "_**vibration**_", but based on the video you provided, the [typewrite_text](https://pub.dev/packages/typewrite_text) package might be more suitable for your needs. 

You can find it here: https://pub.dev/packages/typewrite_text
