### ISSUE TITLE
StateError Bad state: No element

### ISSUE THREAD

**Issue by wwvuillemot** [Nialixus/typewritertext#19]
### Describe the bug

We are seeing this from Sentry.io.

typewriter_value.dart in TypeWriterValue.text at line 87 within typewritertext
typewriter.dart in _X.build.<fn>.<fn> at line 229 within typewritertext

https://github.com/Nialixus/typewritertext/blob/2f081beace2772cf4627ec0e7739fe418d25bfef/lib/v3/typewriter_value.dart#L87

### To Reproduce

1. **Setup:**
   - Flutter version: Flutter 3.24.2 (stable) 
   - Dart version: Dart 3.5.2 (stable)
   - Operating System: iOS 17.5.1

2. **Steps:**
  - not able to reproduce; looking to log the String we are sending to TypeWriter

### Context

While we cannot reproduce reliably, we are seeing it in production on occasion.  In inspecting the code, we note that it's possible that if one of the `index` added to `indexes` is empty then this would explain the error.

In particular, we note in `[typewriter_value.dart around line 76](https://github.com/Nialixus/typewritertext/blob/2f081beace2772cf4627ec0e7739fe418d25bfef/lib/v3/typewriter_value.dart#L76)` there is no check for `item.runes.length`.  If this is `0` then you will create an empty index.  And this will trip an error then at line 82

Current Code
```List<List<int>> get _indexes {
    var current = 0;
    var indexes = <List<int>>[];
    for (String item in data) {
      var index = <int>[];
      for (int i = 0; i < item.runes.length; i++) { # this could be item.rune.length == 0
        index.add(current + i);
      }
      indexes.add(index); # if 0 then this an empty index
      current += item.runes.length;
    }
    return indexes;
  }
```

A proposed fix would just ensure the that `item.runes.length` is non-zero within the loop and skipping that `item` if so.

```List<List<int>> get _indexes {
    var current = 0;
    var indexes = <List<int>>[];
    for (String item in data) {
      if (item.runes.length == 0){
          continue;  # defensively block in case runes.length is 0
      }
      var index = <int>[];
      for (int i = 0; i < item.runes.length; i++) { # this could be item.rune.length == 0
        index.add(current + i);
      }
      indexes.add(index); # if 0 then this an empty index
      current += item.runes.length;
    }
    return indexes;
  }
```

**Comment by Nialixus** [comment]
Hey man, thanks for the heads-up.
I’ve added a try-catch block to handle returning the text. Let me know if the issue persists.

[TypewriterText v3.0.9](https://pub.dev/packages/typewritertext/versions/3.0.9)

**Comment by wwvuillemot** [comment]
Thanks!  Will update and see if we see elimination of error.
