### ISSUE TITLE
Text is truncated

### ISSUE THREAD

**Issue by jjack-flash** [Nialixus/typewritertext#2]
Sorry to say that the issue I previously reported has re-occurred.  See image.

It seems to happen more often when my system is under heavy load.  I'm on an 8th gen intel laptop and running android studio is almost too much for it.

![Screenshot 2023-08-30 152253](https://github.com/Nialixus/typewritertext/assets/59496186/3584192f-d43a-4198-8033-0d4da3cf1b42)

**Comment by Nialixus** [comment]
Sorry for the late response.
I updated to the newer version in v2.0.0 by replacing the `Timer` with `TickerProvider`.

**Comment by jjack-flash** [comment]
That's working perfectly now.  Thank you.
