### ISSUE TITLE
Seeking advice and assistance

### ISSUE THREAD

**Issue by fqingyang** [Nialixus/typewritertext#20]
Thank you very much for your contribution. I am a bit confused and would like to ask for your help now. When I am using TypeWriteController.fromStream, the content of SSEClient. subscribeToSSE returns very quickly, so it looks like it is returned in one go without any typing effect. How should I set the duration or do you have any other suggestions? Thank you very much!

**Comment by Nialixus** [comment]
In order to provide a clearer explanation and help you with using my package, it would be helpful for me to review the code you've written. This way, I can better understand the specific issue you're facing and guide you more effectively.

**Comment by fqingyang** [comment]
抱歉,我的英语不太好以至于描述的不太清楚, 比如我发起一次请求,在很短的时间内内容分十次返回完毕,因为10次间隔的时间非常短, 几乎瞬时所有的内容就返回了并渲染到页面上, 没有打字效果的动画,代码如下:
class AiTransViewLogic extends GetxController {
  final streamController = StreamController<String>();
  final story = "0115";
  final question = "Hi";
  final DialogEntity message;
  AiTransViewLogic(this.message);
  bool isLoading = true;
﻿
  @override
  void onInit() {
    super.onInit();
    // chat();
    var temStr = '';
    if (message.text.isEmpty) {
      SSEClient.subscribeToSSE(method: SSERequestType.POST, url: Api.initDialog, header: {
        "Content-Type": "application/json",
        "Authorization": appController.token
      }, body: {
        "story": story,
        "questions": question,
      }).listen(
        (event) {
          var content = jsonDecode(event.data!)['body'];
          if (isLoading) {
            isLoading = false;
            update();
          }
          if (content != "[DONE]") {
            var delt = JsonConvert.fromJsonAsT<SseResEntity>(jsonDecode(content));
            var item = delt?.choices.first.delta;
            var finishReason = delt?.choices.first.finish_reason;
            if (finishReason == "stop") {
              debugPrint(' finishReason:$finishReason:');
            } else {
              streamController.add(item.content);
              temStr = "$temStr${item.content}";
            }
          } else {
            debugPrint(' content:[DONE]:');
            message.text = temStr;
          }
        },
      );
    }
  }
﻿
  @override
  void onClose() {
    SSEClient.unsubscribeFromSSE();
    streamController.close();
    super.onClose();
  }
}
﻿
class AiTransViewPage extends StatelessWidget {
  final DialogEntity message;
  final DialogPracticeLogic pageLogic;
﻿
  AiTransViewPage({Key? key, required this.message, required this.pageLogic}) : super(key: key);
  bool showTrans = false;
﻿
  @override
  Widget build(BuildContext context) {
    final AiTransViewLogic logic = Get.put(AiTransViewLogic(message));
    const radius = Radius.circular(20);
    return GetBuilder<AiTransViewLogic>(builder: (logic) {
      if (!logic.isLoading) {
        return Container(
          width: 1.sw - (15 + 35 + 5 + 40 + 15),
          padding: const EdgeInsets.only(left: 15, right: 15, top: 15, bottom: 5),
          decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.only(topRight: radius, bottomRight: radius, bottomLeft: radius)),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              if (message.text.isNotEmpty)
                Text(message.text)
              else
                TypeWriter(
                    controller: TypeWriterController.fromStream(
                      logic.streamController.stream,
                    ),
                    builder: (context, value) {
                      return SizedBox(
                        width: double.infinity,
                        child: Text(
                          value.text,
                          textAlign: TextAlign.left,
                        ),
                      );
                    }),
              if (showTrans) Gap.H10,
              if (showTrans) Text(message.translateText),
              Gap.H5,
              Row(
                children: [
                  ClickWidget(
                    onTap: () {
                      pageLogic.startPlayer(message.audioPath);
                      pageLogic.playID.value = message.id;
                    },
                    contentPadding: const EdgeInsets.all(5),
                    child: Image.asset(
                      Assets.icSpeakSound,
                      width: 24,
                      height: 24,
                    ),
                  ),
                  Gap.W10,
                  ClickWidget(
                    onTap: () async {
                      // if (message.translateText.isEmpty) {
                      //   EasyLoading.show();
                      //   RawData? data = await logic.translate({'text': widget.message.text, 'to': 'auto'});
                      //   var result = jsonDecode(data?.value);
                      //   widget.message.translateText = result["translation"][0];
                      // }
                      // showTrans = !showTrans;
                    },
                    contentPadding: const EdgeInsets.all(5),
                    child: Image.asset(
                      showTrans ? Assets.icSpeakTransCheck : Assets.icSpeakTransNormal,
                      width: 20,
                      height: 20,
                    ),
                  ),
                  const Spacer(),
                  ClickWidget(
                    onTap: () {
                      message.isShowTip = false;
                      pageLogic.update();
                    },
                    contentPadding: const EdgeInsets.all(5),
                    child: Image.asset(
                      Assets.show,
                      width: 24,
                      height: 24,
                    ),
                  ),
                ],
              )
            ],
          ),
        );
      } else {
        return Row(
          children: [
            Container(
              width: 50,
              height: 50,
              alignment: Alignment.bottomCenter,
              child: const SVGASimpleImage(
                assetsName: Assets.speakLoading,
              ),
            ),
          ],
        );
      }
    });
  }
}
﻿
class AiTransViewPage extends StatelessWidget {
  final DialogEntity message;
﻿
  AiTransViewPage({Key? key, required this.message}) : super(key: key);
  bool showTrans = false;
﻿
  @override
  Widget build(BuildContext context) {
    final AiTransViewLogic logic = Get.put(AiTransViewLogic(message));
    const radius = Radius.circular(20);
    return GetBuilder<AiTransViewLogic>(builder: (logic) {
      if (!logic.isLoading) {
        return Container(
          width: 1.sw - (15 + 35 + 5 + 40 + 15),
          padding: const EdgeInsets.only(left: 15, right: 15, top: 15, bottom: 5),
          decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.only(topRight: radius, bottomRight: radius, bottomLeft: radius)),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              if (message.text.isNotEmpty)
                Text(message.text)
              else
                TypeWriter(
                    controller: TypeWriterController.fromStream(
                      logic.streamController.stream,
                    ),
                    builder: (context, value) {
                      return SizedBox(
                        width: double.infinity,
                        child: Text(
                          value.text,
                          textAlign: TextAlign.left,
                        ),
                      );
                    }),
        
            ],
          ),
        );
      } else {
        return Row(
          children: [
            Container(
              width: 50,
              height: 50,
              alignment: Alignment.bottomCenter,
              child: const SVGASimpleImage(
                assetsName: Assets.speakLoading,
              ),
            ),
          ],
        );
      }
    });
  }
}

**Comment by fqingyang** [comment]
Sorry, my English is not very good and my description is not very clear. For example, when I initiate a request, the content is returned in ten parts in a very short time. Because the interval between the ten parts is very short, almost all the content is returned and rendered to the page in an instant. There is no animation with typing effect. The code is as follows:
`class AiTransViewLogic extends GetxController {
  final streamController = StreamController<String>();
  final story = "0115";
  final question = "Hi";
  final DialogEntity message;
  AiTransViewLogic(this.message);
  bool isLoading = true;

  @override
  void onInit() {
    super.onInit();
    // chat();
    var temStr = '';
    if (message.text.isEmpty) {
      SSEClient.subscribeToSSE(method: SSERequestType.POST, url: Api.initDialog, header: {
        "Content-Type": "application/json",
        "Authorization": appController.token
      }, body: {
        "story": story,
        "questions": question,
      }).listen(
        (event) {
          var content = jsonDecode(event.data!)['body'];
          if (isLoading) {
            isLoading = false;
            update();
          }
          if (content != "[DONE]") {
            var delt = JsonConvert.fromJsonAsT<SseResEntity>(jsonDecode(content));
            var item = delt?.choices.first.delta;
            var finishReason = delt?.choices.first.finish_reason;
            if (finishReason == "stop") {
              debugPrint(' finishReason:$finishReason:');
            } else {
              debugPrint('item.content: ${item!.content}');
              streamController.add(item.content);
              temStr = "$temStr${item.content}";
            }
          } else {
            debugPrint(' content:[DONE]:');
            message.text = temStr;
            SSEClient.unsubscribeFromSSE();
          }
        },
      );
    }
  }

  @override
  void onClose() {
    SSEClient.unsubscribeFromSSE();
    streamController.close();
    super.onClose();
  }
}`
`class AiTransViewPage extends StatelessWidget {
  final DialogEntity message;

  AiTransViewPage({Key? key, required this.message}) : super(key: key);
  bool showTrans = false;

  @override
  Widget build(BuildContext context) {
    final AiTransViewLogic logic = Get.put(AiTransViewLogic(message));
    const radius = Radius.circular(20);
    return GetBuilder<AiTransViewLogic>(builder: (logic) {
      if (!logic.isLoading) {
        return Container(
          width: 1.sw - (15 + 35 + 5 + 40 + 15),
          padding: const EdgeInsets.only(left: 15, right: 15, top: 15, bottom: 5),
          decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.only(topRight: radius, bottomRight: radius, bottomLeft: radius)),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              if (message.text.isNotEmpty)
                Text(message.text)
              else
                TypeWriter(
                    controller: TypeWriterController.fromStream(
                      logic.streamController.stream,
                    ),
                    builder: (context, value) {
                      return SizedBox(
                        width: double.infinity,
                        child: Text(
                          value.text,
                          textAlign: TextAlign.left,
                        ),
                      );
                    }),
            ],
          ),
        );
      } else {
        return Row(
          children: [
            Container(
              width: 50,
              height: 50,
              alignment: Alignment.bottomCenter,
              child: const SVGASimpleImage(
                assetsName: Assets.speakLoading,
              ),
            ),
          ],
        );
      }
    });
  }
}`

**Comment by fqingyang** [comment]
Sorry, my English is not very good and my description is not very clear. For example, when I initiate a request, the content is returned in ten parts in a very short time. Because the interval between the ten parts is very short, almost all the content is returned and rendered to the page in an instant. There is no animation with typing effect. The code is as follows:

**Comment by fqingyang** [comment]
```dart
class AiTransViewLogic extends GetxController {
  final streamController = StreamController<String>();
  final story = "0115";
  final question = "Hi";
  final DialogEntity message;
  AiTransViewLogic(this.message);
  bool isLoading = true;

  @override
  void onInit() {
    super.onInit();
    // chat();
    var temStr = '';
    if (message.text.isEmpty) {
      SSEClient.subscribeToSSE(method: SSERequestType.POST, url: Api.initDialog, header: {
        "Content-Type": "application/json",
        "Authorization": appController.token
      }, body: {
        "story": story,
        "questions": question,
      }).listen(
        (event) {
          var content = jsonDecode(event.data!)['body'];
          if (isLoading) {
            isLoading = false;
            update();
          }
          if (content != "[DONE]") {
            var delt = JsonConvert.fromJsonAsT<SseResEntity>(jsonDecode(content));
            var item = delt?.choices.first.delta;
            var finishReason = delt?.choices.first.finish_reason;
            if (finishReason == "stop") {
              debugPrint(' finishReason:$finishReason:');
            } else {
              debugPrint('item.content: ${item!.content}');
              streamController.add(item.content);
              temStr = "$temStr${item.content}";
            }
          } else {
            debugPrint(' content:[DONE]:');
            message.text = temStr;
            SSEClient.unsubscribeFromSSE();
          }
        },
      );
    }
  }

  @override
  void onClose() {
    SSEClient.unsubscribeFromSSE();
    streamController.close();
    super.onClose();
  }
}
class AiTransViewPage extends StatelessWidget {
  final DialogEntity message;

  AiTransViewPage({Key? key, required this.message}) : super(key: key);
  bool showTrans = false;

  @override
  Widget build(BuildContext context) {
    final AiTransViewLogic logic = Get.put(AiTransViewLogic(message));
    const radius = Radius.circular(20);
    return GetBuilder<AiTransViewLogic>(builder: (logic) {
      if (!logic.isLoading) {
        return Container(
          width: 1.sw - (15 + 35 + 5 + 40 + 15),
          padding: const EdgeInsets.only(left: 15, right: 15, top: 15, bottom: 5),
          decoration: const BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.only(topRight: radius, bottomRight: radius, bottomLeft: radius)),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            children: [
              if (message.text.isNotEmpty)
                Text(message.text)
              else
                TypeWriter(
                    controller: TypeWriterController.fromStream(
                      logic.streamController.stream,
                    ),
                    builder: (context, value) {
                      return SizedBox(
                        width: double.infinity,
                        child: Text(
                          value.text,
                          textAlign: TextAlign.left,
                        ),
                      );
                    }),
            ],
          ),
        );
      } else {
        return Row(
          children: [
            Container(
              width: 50,
              height: 50,
              alignment: Alignment.bottomCenter,
              child: const SVGASimpleImage(
                assetsName: Assets.speakLoading,
              ),
            ),
          ],
        );
      }
    });
  }
}
```

**Comment by fqingyang** [comment]
What I want to ask is how to set the duration parameter when using TypeWriteController.fromStream, the lay time between each Listen response,the lay time between each Listen response,Thus showcasing the typing animation effect

**Comment by Nialixus** [comment]
try this

```dart
import 'dart:async';

class AiTransViewLogic extends GetxController {
  final streamController = StreamController<String>();
  final story = "0115";
  final question = "Hi";
  final DialogEntity message;
  AiTransViewLogic(this.message);
  bool isLoading = true;

  @override
  void onInit() {
    super.onInit();
    var temStr = '';
    if (message.text.isEmpty) {
      SSEClient.subscribeToSSE(
        method: SSERequestType.POST,
        url: Api.initDialog,
        header: {
          "Content-Type": "application/json",
          "Authorization": appController.token,
        },
        body: {
          "story": story,
          "questions": question,
        },
      ).listen(
        (event) async {
          var content = jsonDecode(event.data!)['body'];
          if (isLoading) {
            isLoading = false;
            update();
          }
          if (content != "[DONE]") {
            var delt = JsonConvert.fromJsonAsT<SseResEntity>(jsonDecode(content));
            var item = delt?.choices.first.delta;
            var finishReason = delt?.choices.first.finish_reason;
            if (finishReason == "stop") {
              debugPrint('finishReason: $finishReason');
            } else {
              debugPrint('item.content: ${item!.content}');
              // Emit the text content one character at a time with a delay
              for (int i = 0; i < item.content.length; i++) {
                await Future.delayed(const Duration(milliseconds: 100)); // Adjust delay time as needed
                streamController.add(item.content[i]);
                temStr = "$temStr${item.content[i]}";
              }
            }
          } else {
            debugPrint('content: [DONE]');
            message.text = temStr;
            SSEClient.unsubscribeFromSSE();
          }
        },
      );
    }
  }

  @override
  void onClose() {
    SSEClient.unsubscribeFromSSE();
    streamController.close();
    super.onClose();
  }
}
```

so basically you make the event listener `async` and add delay in the `else` function

```dart
else {
  debugPrint('item.content: ${item!.content}');
  
  // Emit the text content one character at a time with a delay
  for (int i = 0; i < item.content.length; i++) {
    await Future.delayed(const Duration(milliseconds: 100)); // Adjust delay time as needed
    streamController.add(item.content[i]);
    temStr = "$temStr${item.content[i]}";
  }
}
```

Though I'd suggest using StreamBuilder as it offers more flexibility

**Comment by fqingyang** [comment]
Thank you very much! I will give it a try
