### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug'.

### ISSUE THREAD

**Issue by HammadNasir** [Nialixus/typewritertext#5]
../AppData/Local/Pub/Cache/hosted/pub.dev/typewritertext-2.3.1/lib/typewritertext.dart:184:17: Error: No named parameter with the name 'textScaler'.
                textScaler: text.textScaler ?? TextScaler.noScaling,
                ^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/painting/text_painter.dart:489:3: Context: Found this candidate, but the arguments don't match.
  TextPainter({
  ^^^^^^^^^^^
../AppData/Local/Pub/Cache/hosted/pub.dev/typewritertext-2.3.1/lib/typewritertext.dart:205:19: Error: No named parameter with the name 'textScaler'.
                  textScaler: text.textScaler,
                  ^^^^^^^^^^
/C:/src/flutter/packages/flutter/lib/src/widgets/text.dart:428:9: Context: Found this candidate, but the arguments don't match.
  const Text(
        ^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Nialixus** [comment]
Sorry for the late reply, I've already remove the scaler in v3.0.0
