### ISSUE TITLE
Dynamic text change is not working

### ISSUE THREAD

**Issue by Hardeepdrish** [Nialixus/typewritertext#7]
Text changes with state management is not working it gives error  Incorrect use of ParentDataWidget.

**Comment by Nialixus** [comment]
Could you give me the stacktrace

**Comment by Hardeepdrish** [comment]
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Padding widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  MouseRegion ← TextField ← Expanded ← Padding ← Column ← Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#49ee3 ink renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:6512:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6529:6)
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5847:15)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5849:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5523:14)
#6      ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:5852:5)
#7      ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:5895:5)
#8      ProxyElement.updated (package:flutter/src/widgets/framework.dart:5810:5)
#9      ProxyElement.update (package:flutter/src/widgets/framework.dart:5799:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#13     Element.updateChildren (package:flutter/src/widgets/framework.dart:3964:32)
#14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6896:17)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6743:14)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:3815:15)
#18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496:16)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#20     ProxyElement.update (package:flutter/src/widgets/framework.dart:5800:5)

**Comment by Nialixus** [comment]
Hmm, it doesn't have a reference to this package. Your problem seems to be related to placing the Expanded widget inside a Padding widget, which won't work. Instead, whenever you want to use Expanded, you should place it inside a Row, Column, or another flex widget.

Since the issue appears to be unrelated to this package, I'm considering closing this matter. If you have further questions or concerns related to this package, please feel free to reopen or create a new issue. Thank you for your understanding!

**Comment by Hardeepdrish** [comment]
Hi, This stacktrace is may not useful for you, but my concern is can i use widget for dynamic/run time text. For const String it works fine.

Example:  TypeWriterText(
                  text: Text(runTimeString),
                  duration: Duration(milliseconds: 50),
                ),

This is not working when runTimeString chnages.

**Comment by Nialixus** [comment]
To better understand, I need to see your full code because the error you mentioned earlier was related to a layout issue, possibly misusing the expanded widget. Additionally, it doesn't seem that the issue was coming from the typewriter widget itself.

**Comment by Nialixus** [comment]
The TypeWriterText widget doesn't update when the runTimeString changes because it only works with final String. You can use a a wrapper widget that allows for dynamic/run time text updates, such as ListenableBuilder or FutureBuilder.
