### ISSUE TITLE
Last word in text doesn't appear 

### ISSUE THREAD

**Issue by sayedmoataz** [Nialixus/typewritertext#8]
I have an issue that while using the package it's working very well, but there's an issue that the last word in text doesn't appear since I change the state it appear 
here's a video that explain what I mean 
TypeWriterText : what's your name how are you 
first time it was ```what's your name how are``` 
then when state changed it gone to be ```what's your name how are you```

https://github.com/Nialixus/typewritertext/assets/46425858/17182c12-6c20-4067-ba59-719cc1b724e0

this is my code 
```
TypeWriterText(
      text: Text(
        text,
        textAlign: TextAlign.left,
        style: TextStyle(
            fontSize: 11.sp,
            fontWeight: FontWeight.w400,
            height: 2,
            color: AppColors.whiteColor),
      ),
      duration: const Duration(milliseconds: 5),
    )
```

**Comment by Muzm** [comment]
@sayedmoataz I checked source code. find out every character is shown, but by default `TypeWriterText.maintanSize` is `true`. I believe text was overflowed,  hide by the `TextOverflow.hide`. so, set `maintanSize: false` to `TypeWriterText`, everything work fine.

**Comment by Nialixus** [comment]
It's hard to reproduce this issue without seeing the full code.

#### Theoretically:

> 1. This happens because the parent widget rebuilds its descendants. The parent needs to wait to change its state until the `TypeWriterText` finishes using the `onFinished` function.

> 2. When the parent changes state, it skips some frames where the descendant is supposed to display each character, causing it to leap to the last line due to the state change.

It would be very helpful if you could provide the full code from that page.
